### ISSUE TITLE
Script changes to Desktop

### ISSUE THREAD

**Issue by parkerlreed** [ivan-hc/ArchImage#10]
Why does the script change to desktop instead of using the script dir?

**Comment by parkerlreed** [comment]
So I can't use for for CLI programs? I want qemu-system-i386 to run when I call the Appimage. I gave that as a binary name. There will be no icon or desktop file for this.

**Comment by ivan-hc** [comment]
No, you can't port this to an AppImage by default... but you can edit this script and add a .desktop file and an icon by yourself and change the AppRun into this script. All you need are the basic skills to write/edit a bash script. If you already use the command line on Linux for basic things like copy/move/remove files... this should not be a problem for you.

Alternativelly, install this using JuNest directly... and if you want to port this as an AppImage, study what is installed through the qemu-full metapackage.
