### ISSUE TITLE
hi, i see you new version

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/ArchImage#16]
i think bwrap it archimage is not good

because, i see the other to build appimage, is not work
https://github.com/gfdgd-xi/deep-wine-runner

is use bwrap to run program
https://github.com/gfdgd-xi/deep-wine-runner/issues/6

**Comment by newyorkthink** [comment]
and , some program it need kernel model with use bwrap, and i test use bwrap env to run appimage and it need kernel support

**Comment by ivan-hc** [comment]
Sure, the purpose of this new release is to give the AppImage the best compatility as possible with the host system.

Things like internet connection and hardware accelleration from the host are quite impossible with `proot`. JuNest is ment to be used normally with `bwrap`. Infact I need to patch less things in the package.

Normal `proot` implementation we have used until now has its limits that `bwrap` should break with ease.

**Comment by ivan-hc** [comment]
Even [Emacs](https://github.com/ivan-hc/Emacs-appimage) works better than before, I had not to implement additional patches!

Just wait the new release from about 2 minutes.
