### ISSUE TITLE
Arch Package with multiple versions.

### ISSUE THREAD

**Issue by fmc000** [ivan-hc/ArchImage#17]
I'm interested in the swell-foop Gnome game. Arch now lists two releases as show in https://archlinux.org/packages/?q=swell-foop ; the first one (41.1) is buggy as hell whilst the second one (46alpha) works just fine despite being experimental.

archimage-cli builds the first one unfortunately. Can we instruct the script to build the second one instead?

**Comment by ivan-hc** [comment]
The builder is just a script you can edit with any text editor.

You should enable the repository manually.

Read the script and take as an example the steps "# ENABLE MULTILIB (optional)" and "# ENABLE CHAOTIC-AUR".

I was not aware of a "Gnome-Unstable" repo, oly used the official ones and AUR, so I can't be of much help here.
