### ISSUE TITLE
Pipewalker AppImage fails to build

### ISSUE THREAD

**Issue by fmc000** [ivan-hc/ArchImage#18]
This is a strange one. The build fails almost at the end saying it doesnt fine "pipewalker.xpm", which is actually present inside the AppDir. I just tried to build the appimage with all the default options so this issued should be pretty easy to replicate.

**Comment by ivan-hc** [comment]
Let me see the part of the log where the scrips fails. I'm sure there is a missing .desktop file in the root of the AppDir.

**Comment by fmc000** [comment]
Actually I was able to make the AppImage by modifying the .desktop file by
removing the "xpm" extension from the icon entry and rebuilding. It looks
like the .desktop file originally shipped from the AUR contains a
deprecated icon entry.

Il giorno mar 27 feb 2024 alle ore 19:17 iVAN ***@***.***> ha
scritto:

**Comment by ivan-hc** [comment]
So you should include the dedicated audio driver, I don't know how this app works, but you should add the missing dependence in "DEPENDENCES=" and let the script include it in the AppImage package.

**Comment by atirage21** [comment]
**Answer only for fmc000.** I saw that you try build game: Hearts for linux. Please check this: https://github.com/DevoKun/gnome-hearts   and also current issues: https://github.com/DevoKun/gnome-hearts/issues/1
