### ISSUE TITLE
Built script fails to run fully

### ISSUE THREAD

**Issue by robzombie91** [ivan-hc/ArchImage#21]
[output.log](https://github.com/ivan-hc/ArchImage/files/14947523/output.log)

**Comment by ivan-hc** [comment]
To create an AppImage are needed also a .desktop file and an icon for the executable application.

And "pam", does not have them https://archlinux.org/packages/core/x86_64/pam/files/

**Comment by robzombie91** [comment]
In my log I'm trying to built an apoimage for Firefox like one of your examples but it fails like in the output log

**Comment by ivan-hc** [comment]
Like the one in this video?

https://github.com/ivan-hc/ArchImage/assets/88724353/06c91ddf-b9c8-41aa-a68c-325250925fd7

**Comment by ivan-hc** [comment]
@robzombie91 you were right, previously I've done a refactoring of the script and Shellcheck has suggested to put "quotes" were they were missing, als for the arguments in YAY/pacman. Now I've fixed it. Thank you
