### ISSUE TITLE
Protonmail Appimage

### ISSUE THREAD

**Issue by in4matix** [ivan-hc/ArchImage#26]
Hi Ivan,
I am battling, any chance you can assist?
https://proton.me/mail/download

**Comment by ivan-hc** [comment]
By sunning Snap2AppImage I noticed that the "VERSION" finding is the one that is stuck, due to a missing "snapcraft.yaml" file.

Here is how to solve

https://github.com/user-attachments/assets/13c07e5c-6404-4bef-b98b-bbb86e4d8a1b

Here is imstead the content of the "proton-mail.sh" script I have used in this video
```
#!/bin/sh

APP=proton-mail

# TEMPORARY DIRECTORY
mkdir -p tmp
cd ./tmp || exit 1

# WGET VERSION USAGE
_wget_version_usage() {
	if wget --version | head -1 | grep -q ' 1.'; then
		wget -q --show-progress "$@"
	else
		wget "$@"
	fi
}

# DOWNLOAD APPIMAGETOOL
if ! test -f ./appimagetool; then
	_wget_version_usage https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
	chmod a+x ./appimagetool
fi

# DOWNLOAD THE SNAP PACKAGE
if ! test -f ./*.snap; then
	_wget_version_usage "$(curl -H 'Snap-Device-Series: 16' http://api.snapcraft.io/v2/snaps/info/"$APP" --silent | sed 's/[()",{} ]/\n/g' | grep "^http" | head -1)"
fi

# EXTRACT THE SNAP PACKAGE
if ! test -d ./squashfs-root; then
	unsquashfs -f ./*.snap
fi

# FIND PACKAGE VERSION
VERSION=$(cat $(find . -name version | head -1))

# CREATE THE APPDIR AND COMPILE THE APPIMAGE
mkdir -p "$APP".AppDir
rm -Rf ./"$APP".AppDir/*

# FIND THE .DESKTOP FILE AND REPLACE THE "ICON" ENTRY
cp -r "$(find . -name "$APP".desktop | head -1)" ./"$APP".AppDir/
sed -i "s/^Icon=.*/Icon=$APP/g" ./"$APP".AppDir/*.desktop

# FIND THE APPNAME
APPNAME="$(cat ./"$APP".AppDir/*.desktop | grep '^Name=' | head -1 | cut -c 6- | sed 's/ /-/g')"

# FIND THE ICON
cp -r "$(find . -name *.png | grep -i "$APP" | sort | head -1)" ./"$APP".AppDir/"$APP".png 2> /dev/null
cp -r "$(find . -name *.svg | grep -i "$APP" | sort | head -1)" ./"$APP".AppDir/"$APP".svg 2> /dev/null

# IMPORT COMMON LINUX DIRECTORIES
if test -d ./squashfs-root/etc; then cp -r ./squashfs-root/etc ./"$APP".AppDir/; fi
if test -d ./squashfs-root/lib; then cp -r ./squashfs-root/lib* ./"$APP".AppDir/; fi
if test -d ./squashfs-root/usr; then cp -r ./squashfs-root/usr ./"$APP".AppDir/; fi

# APPRUN
cat >> ./"$APP".AppDir/AppRun << 'EOF'
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD=/:"${HERE}"
export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${HERE}"/usr/lib/python*/:"${PYTHONPATH}"
export PYTHONHOME="${HERE}"/usr/:"${HERE}"/usr/lib/python*/
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
export PERLLIB="${HERE}"/usr/share/perl5/:"${HERE}"/usr/lib/perl5/:"${PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
exec ${EXEC} "$@"
EOF
chmod a+x ./"$APP".AppDir/AppRun

# CONVERT THE APPDIR INTO AN APPIMAGE
ARCH=x86_64 ./appimagetool --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 20 ./"$APP".AppDir
cd ..
mv ./tmp/*.AppImage ./"$APPNAME"-"$VERSION"-x86_64.AppImage
```
I hope this would help you.

**Comment by ivan-hc** [comment]
About the Archimage instead, you should find the exact package for proton-mail from the AUR

- https://aur.archlinux.org/packages/proton-mail
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=proton-mail

froma what I have seen in the PKGBUILD, the program is installed in /opt, in AUR, and that is a path I mount by default, due to my package manager "AM". You should add an additional step manually to move the content from /opt to /usr/share... you need a bit to study the script.

Consider using Snap2AppImage instead.

**Comment by ivan-hc** [comment]
@in4matix I have done a test with Archimage, the script I have built was created by including all dependences and using the standard configurations, no extra steps done in `archimage-cli`

However, to solve the issue was enough to add these extra step of three lines manually, before the steps to create the AppImage
```
# EXTRA STEP
sed -i "s#Exec=#Exec=/usr/share/$APP/#g" ./"$APP".AppDir/*.desktop
cd ./"$APP".AppDir/.junest/opt/"$APP"
ln -s Proton\ Mail proton-mail
cd -
if test -d ./"$APP".AppDir/.junest/usr/share/"$APP"; then
	rm -Rf ./"$APP".AppDir/.junest/opt/"$APP"
else
	mv ./"$APP".AppDir/.junest/opt/"$APP" ./"$APP".AppDir/.junest/usr/share/"$APP"
fi
```
the above function:
1. adds the new path of the program in the .desktop file
2. we create a symlink for the binary "Proton Mail" with the name of the app (as the one used in the .desktop file)
3. we move the directory from /opt to /usr/share

The final AppImage is 211 MB.

I'll add the script at https://github.com/ivan-hc/ArchImage/tree/main/drafts to close this issue, and after this, you will know what to do with that script. You can also open you own repo with that.

**Comment by in4matix** [comment]
Thank you very much for all your help.

**Comment by in4matix** [comment]
I get the following when running the script:

```
daniel@dkdt:~/Downloads/XX/Archimage/Tmp$ ./proton-mail-junest.sh
./proton-mail-junest.sh: line 7: syntax error near unexpected token `newline'
./proton-mail-junest.sh: line 7: `<!DOCTYPE html>'
daniel@dkdt:~/Downloads/XX/Archimage/Tmp$
```

**Comment by ivan-hc** [comment]
I don't know, it worked well for me.

At line 7 there is
```
BASICSTUFF="binutils debugedit gzip"
```
I don't get how to set a variable with simple words would give an error.

You were able to runa Archimage scripts until now, isn't it?

**Comment by in4matix** [comment]
> You were able to runa Archimage scripts until now, isn't it?

No, first time, and I'm quite stupid.

**Comment by ivan-hc** [comment]
have you followed all instructions on the README?

**Comment by in4matix** [comment]
> have you followed all instructions on the README?

Yes, several times.. Maybe I am doing something wrong? I didn't use `archimage-cli.sh` at all. I just downloaded the draft script and ran that..

**Comment by ivan-hc** [comment]
is the directory you run the script completelly empty?

**Comment by in4matix** [comment]
> is the directory you run the script completelly empty?

It just contains the draft script.

**Comment by ivan-hc** [comment]
can you do a video to show me the behaviour?

**Comment by in4matix** [comment]
Okay:

[Screencast from 28-09-2024 19:52:57.webm](https://github.com/user-attachments/assets/a6d59362-070c-465b-9dc6-a60c5794631c)

**Comment by ivan-hc** [comment]
let me guess: Fedora 40+, is it right?

**Comment by ivan-hc** [comment]
the first process to be executed should be this
```
if ! test -f ./appimagetool; then
	wget2 -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
	chmod a+x appimagetool
fi
```
are you able to run the above command?

**Comment by in4matix** [comment]
> let me guess: Fedora 40+, is it right?

Ubuntu 22.04 LTS

> are you able to run the above command?

```
daniel@dkdt:~/Downloads$ if ! test -f ./appimagetool; then
        wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
        chmod a+x appimagetool
fi
daniel@dkdt:~/Downloads$
```

NOTE: I didn't have wget2 installed. I had to install it and then run the command again.

**Comment by ivan-hc** [comment]
> NOTE: I didn't have wget2 installed. I had to install it and then run the command again.

I know, sorry, I edited the comment, this is because I have done the test

**Comment by ivan-hc** [comment]
so appimagetool has been downloaded, right?

**Comment by in4matix** [comment]
Yes, it is in Downloads folder.

**Comment by ivan-hc** [comment]
is your shell "bash" or "sh" or something else?

**Comment by in4matix** [comment]
It is bash

**Comment by ivan-hc** [comment]
sorry, I'm googleing to find the reason of the message
```
syntax error near unexpected token `newline'
```

**Comment by in4matix** [comment]
Sorry, as I mentioned, I'm stupid when it comes to coding. scripts and stuff. I just know the basics and quote new to Linux.

**Comment by ivan-hc** [comment]
@Samueru-samu sorry if I always bother you... have you seen here?

> ```
> syntax error near unexpected token `newline'
> ```

if this fails for this script, it fails for all scripts created like this.
