### ISSUE TITLE
No such Directory

### ISSUE THREAD

**Issue by xensurve** [ivan-hc/ArchImage#3]
Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...
grep: /root/Desktop/tmp/.junest/usr/share/applications/*: No such file or directory
cp: cannot stat '': No such file or directory

any app from aur  I try to install gives me this output

**Comment by ivan-hc** [comment]
this part

    grep: /root/Desktop/tmp/.junest/usr/share/applications/*: No such file or directory
    cp: cannot stat '': No such file or directory
means that if you installed something, there is not a *.desktop file in ./.junest/usr/share/applications .... so the app has not been installed. I suggest to repeat the steps manually to test what was wrong during the execution of the script.

PS: I don't know if I should replace AUR with ChaoticAUR, at least to prevent the long compiling process.

**Comment by ivan-hc** [comment]
Just improved the template https://github.com/ivan-hc/ArchImage/commit/910c7cbe76cb4d0cc6722389f142bbfdea0e2f9a

Try to create it again.

PS: due to the amount of disk space, I decided to made optional only `gzip`/`binutils` and `gcc`, but to made all development tools available, use `base-devel` https://archlinux.org/packages/core/any/base-devel/ according with the main guide of JuNest https://github.com/fsquillace/junest#cannot-use-aur-repository

**Comment by ivan-hc** [comment]
New template https://github.com/ivan-hc/ArchImage/commit/011de7fbdf4cba53998e6ca90be7becd5a36bfe5

    ./archimage-cli -b name-of-the-package-from-aur
I've just created a new repo for "Bottles" with this template https://github.com/ivan-hc/Bottles-appimage

**Comment by ivan-hc** [comment]
> Firefox

I have troubles with apps requiring internet connections (you've tested this with Firefox, I've done the same with Chromium). I think I should to remove `2> /dev/null` from the AppRun to see more details... however, those who want to learn more about the created app, can do the same by testing the AppRun into ./*.AppDir

> 1 ) applications that don't have a desktop file and has either has one or more files and runs in the terminal i.e aircrack-ng

so I should add an "if" function in case *.desktop is not in ./*.Appdir and use `touch` to generate an empty icon to made these apps exportable as AppImages. This is a good idea.

> 2 ) use chaotic to speed up and have smaller space

I've seen that there is not everything in chaotic, yesterday I've seen if `gimp-devel` was there, I've found `gimp-git` and I think it is not the same thing. So to leave everything as is its the better idea. I think that those who want to create this kind of Appimage need to use a web service like Github Actions, Open Build Service or Travis to generate these apps automatically. I recommend to test this one or two times on the PC, then start the search to remove stuff.

> 3 ) add > /dev/null 2>&1 to ignore output if folder exists etc

I think I've already provided something like this, however those that have a less powerful CPU (I have an AMD Ryzen 5 3600) can be not aware about the amount of time compiling the Appimage and may think the program is stuck!

**Comment by ivan-hc** [comment]
Today I've replaced VLC, GIMP and GIMP Developer Edition (gimp-dev) using the new template, updated MPV and OBS Studio... and yesterday I opened a repository for an experimental "Bottles"... all works fine and with no errors. 

I think that its enough to made this issue solved.
