### ISSUE TITLE
how can you build don't show package contents use Archimage in arch package website details

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/ArchImage#8]
some package contents is not show
![image](https://github.com/ivan-hc/ArchImage/assets/87791643/ca9f39cd-f4cd-4141-911e-f7506e35d591)

i means , it not have /usr/bin/...

**Comment by ivan-hc** [comment]
No way to know this before you have finished to compile the package from AUR on Arch Linux.

AUR does not stores prebuilt packages, it contains scripts to compile them on your PC (this may take a lot of time).

From AUR you need to compile it first, then you will know what are the binaries and desktop files.

This is an information that laks in AUR, so you should compile the file by yourself.

First of all test it on JuNest and do your studies on the results.

ArchImage-cli is for those that know what to install and how the apps are installed (in particular from AUR).

So study what is Arch Linux, how AUR works and then study what is installed from AUR.
